version: '3.7'
services:

  mongo:
    image: mongo:4.2.3
    environment:
      - "MONGO_INITDB_ROOT_USERNAME:root"
      - "MONGO_INITDB_ROOT_PASSWORD:root"
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME:root"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD:root"
  iotapp:
    image: ragulmathawa/iotapp-master:1.0
    ports:
      - "3000:3000"
    environment:
      - "PORT=3000"
